[package]
name = "ipmap"
version = "0.1.0"
authors = ["Aditya Suresh <ethanaditya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
