[package]
name = "ipmap"
version = "0.1.0"
authors = ["Aditya Suresh <ethanaditya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.7.0"
etherparse = "0.9.0"
ureq = "1.5.1"
serde_json = "1.0.59"
casual_logger = "0.6.5"
open = "1.4.0"
