["Now=2020-11-07T16:25:15-0700&Pid=72319&Thr=ThreadId(1)&Seq=1"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:25:16-0700&Pid=72319&Thr=ThreadId(1)&Seq=2"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:25:17-0700&Pid=72319&Thr=ThreadId(1)&Seq=3"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:25:17-0700&Pid=72319&Thr=ThreadId(1)&Seq=4"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:25:18-0700&Pid=72319&Thr=ThreadId(1)&Seq=5"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:25:18-0700&Pid=72319&Thr=ThreadId(1)&Seq=6"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:25:20-0700&Pid=72319&Thr=ThreadId(1)&Seq=7"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:25:20-0700&Pid=72319&Thr=ThreadId(1)&Seq=8"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:25:21-0700&Pid=72319&Thr=ThreadId(1)&Seq=9"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:25:21-0700&Pid=72319&Thr=ThreadId(1)&Seq=10"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:25:22-0700&Pid=72319&Thr=ThreadId(1)&Seq=11"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:28-0700&Pid=73022&Thr=ThreadId(1)&Seq=1"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:29-0700&Pid=73022&Thr=ThreadId(1)&Seq=2"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:30-0700&Pid=73022&Thr=ThreadId(1)&Seq=3"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:30-0700&Pid=73022&Thr=ThreadId(1)&Seq=4"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:31-0700&Pid=73022&Thr=ThreadId(1)&Seq=5"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:31-0700&Pid=73022&Thr=ThreadId(1)&Seq=6"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:32-0700&Pid=73022&Thr=ThreadId(1)&Seq=7"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:33-0700&Pid=73022&Thr=ThreadId(1)&Seq=8"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:33-0700&Pid=73022&Thr=ThreadId(1)&Seq=9"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:33-0700&Pid=73022&Thr=ThreadId(1)&Seq=10"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:34-0700&Pid=73022&Thr=ThreadId(1)&Seq=11"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:34-0700&Pid=73022&Thr=ThreadId(1)&Seq=12"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:34-0700&Pid=73022&Thr=ThreadId(1)&Seq=13"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:35-0700&Pid=73022&Thr=ThreadId(1)&Seq=14"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:35-0700&Pid=73022&Thr=ThreadId(1)&Seq=15"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:35-0700&Pid=73022&Thr=ThreadId(1)&Seq=16"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:36-0700&Pid=73022&Thr=ThreadId(1)&Seq=17"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:36-0700&Pid=73022&Thr=ThreadId(1)&Seq=18"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:36-0700&Pid=73022&Thr=ThreadId(1)&Seq=19"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:37-0700&Pid=73022&Thr=ThreadId(1)&Seq=20"]
Error = 'Unable to find latitude in parsed JSON'

["Now=2020-11-07T16:26:37-0700&Pid=73022&Thr=ThreadId(1)&Seq=21"]
Error = 'Unable to find latitude in parsed JSON'

